[versions]

kotlin = "2.4.0"
kotlinxSerialization = "1.11.0"
kotlinxDatetime = "0.8.0"
junit = "5.14.4"

# Benchmark-only libraries
jmh = "1.37"
ktoml = "0.7.1"
jackson = "2.22.0"
nightConfig = "3.8.4"
tomlj = "1.1.1"

# Plugins
dokka = "2.2.0"
detekt = "1.23.8"
jmhPlugin = "0.7.3"
mavenPublish = "0.36.0"

[libraries]

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

# Benchmark-only libraries
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
jackson-dataformat-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
night-config-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightConfig" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }

[plugins]

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhPlugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
